### ISSUE TITLE
Create On boarding screen

### ISSUE THREAD

**Issue by AryanC19** [ACM-VIT/muscle_magic#25]
Just the basic functionality to be implemented

3 Screens-
First has an image and a text widget  "Measure your progress"
The second has an image and a text widget "Compete with other users"
The third has an image and a text widget "You are ready!"

Use any sample image

[https://pub.dev/packages/onboarding](url)
for reference

**Comment by PrajwalGKale** [comment]
## Greetings, @AryanC19 
>**I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Flutter framework* .**

**Comment by PrajwalGKale** [comment]
@AryanC19 ,
> *I can make the On boarding screen of 3 pages by the help of this package.*
     [https://pub.dev/packages/flutter_onboarding_slider](url)

**Comment by AryanC19** [comment]
> @AryanC19 ,
> 
> > _I can make the On boarding screen of 3 pages by the help of this package._
> > [https://pub.dev/packages/flutter_onboarding_slider](url)

Sure

**Comment by PrajwalGKale** [comment]
Hello **@AryanC19**,
 > For the onboarding screen, it is possible to use any fitness-related image from the internet.

**Comment by AryanC19** [comment]
> Hello **@AryanC19**,
> 
> > For the onboarding screen, it is possible to use any fitness-related image from the internet.

Yes, since the designs aren't finalized you can use any sample image for now

**Comment by PrajwalGKale** [comment]
## Hello **@AryanC19** , 
> I make a PR Please review.
   I hope you will like it.

**Comment by PrajwalGKale** [comment]
## Hello **`@AryanC19`** 
> I made a PR Please review. **If everything is fine, merge it**.

**Comment by lio2011** [comment]
Can a simple figma design also work as well?
