### ISSUE TITLE
Add API calls to get excercise list

### ISSUE THREAD

**Issue by Harsh-Vipin** [ACM-VIT/muscle_magic#3]
- API calls need to be added to get  the list of exercises 
- The list of exercises should be displayed in the exercises screen
-  Use https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/details for the api ( use the free subscription for api key)
- Add the file in path Networking/[file name]
- Follow the guidelines and do attach screenshots

**Comment by gautamjain09** [comment]
Hey! Can you assign this issue to me?

**Comment by AryanC19** [comment]
Sure

**Comment by Harsh-Vipin** [comment]
> Hey! Can you assign this issue to me?

Do inform if facing any issues

**Comment by gautamjain09** [comment]
> > Hey! Can you assign this issue to me?
> 
> Do inform if facing any issues

It is almost done I am just debugging render overflows

**Comment by Harsh-Vipin** [comment]
> > > Hey! Can you assign this issue to me?
> > 
> > 
> > Do inform if facing any issues
> 
> It is almost done I am just debugging render overflows

Cool 👍

**Comment by gautamjain09** [comment]
Can you give me your discord ID? need to discuss about API

**Comment by Harsh-Vipin** [comment]
> Can you give me your discord ID? need to discuss about API

Harsh v#5439
