### ISSUE TITLE
Add app logo

### ISSUE THREAD

**Issue by AryanC19** [ACM-VIT/muscle_magic#4]
Add the app logo for android

**Comment by vamsikrishnarh7** [comment]
Hey! Can you assign this issue to me?

**Comment by AryanC19** [comment]
Sure!

**Comment by AryanC19** [comment]
Sure,good luck.

**Comment by Harsh-Vipin** [comment]
> Hey! Can you assign this issue to me?

How is the progress?

**Comment by SanjaySargam** [comment]
Plz assign me

**Comment by Harsh-Vipin** [comment]
> Plz assign me

Done

**Comment by AryanC19** [comment]
> Plz assign me

What is the progress?

**Comment by SanjaySargam** [comment]
Which logo we have to add

**Comment by Harsh-Vipin** [comment]
> Which logo we have to add

Design a logo for the app and add it to the assets folder

**Comment by SanjaySargam** [comment]
> > Which logo we have to add
> 
> Design a logo for the app and add it to the assets folder

ok

**Comment by Arsh-78** [comment]
Hello Can you assign it to me simultaneously,I will finish it asap

**Comment by sowmiya-venkatesan** [comment]
Hi @AryanC19 Could you please assign me this issue?

**Comment by AryanC19** [comment]
> Hello Can you assign it to me simultaneously,I will finish it asap

Plz do
