### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by AryanC19** [ACM-VIT/muscle_magic#5]
- Add splash screen for both android and ios
-  Use native splash package
-  Use any random free logo
- Follow the guidelines and do attach the screenshots

**Comment by SmartAree** [comment]
Can I work on this?

**Comment by SmartAree** [comment]
Thanks.

**Comment by SanjaySargam** [comment]
Can u plz assign me. I want to work on this

**Comment by Harsh-Vipin** [comment]
> No please I am working on this. :O @Harsh-Vipin @AryanC19

Cool carry on

**Comment by Harsh-Vipin** [comment]
> Can u plz assign me. I want to work on this

You could work on #18  if you want to (:

**Comment by SmartAree** [comment]
@Harsh-Vipin  there is no logo.png file in the assets or images folder.

**Comment by Harsh-Vipin** [comment]
> @Harsh-Vipin there is no logo.png file in the assets or images folder.

As mentioned in the description use any random free logo from the internet and add it to the assets folder
